version: '3.8'
x-environment-defaults: &environment-defaults
  DEBUG: True
  DB_NAME: "blog_adv_docker"
  DB_USER: "nikitagrebnev"
  DB_PASSWORD: "1"
  DB_HOST: "db"
  DB_PORT: 5432
  SECRET_KEY: "django-insecure-fl^3v^e@q=z)=z+s7%jwfv7a=i-f5z83k%b5s-ndmb10u+q33h"
  EMAIL_HOST_USER: "ngrebnev17@gmail.com"
  EMAIL_HOST_PASSWORD: "foeu ihjq gdan frde"
  REDIS_HOST: "redis"


services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: nikitagrebnev
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: blog_adv_docker
    ports:
      - "5432:5432"

  blog_adv:
    container_name: blog_adv
    build:
      context: ./
    ports:
      - "8001:8000"
    depends_on:
      - db
    environment:
      <<: *environment-defaults
    volumes:
      - static_volume:/app/static
    restart: on-failure:5
    healthcheck:
      test: curl -f http://localhost:8000/api/v1/health || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/static
    ports:
      - "80:80"
    depends_on:
      - blog_adv

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    container_name: celery
    build:
      context: ./
    command: celery -A config worker -l INFO
    depends_on:
      - redis
      - db
    environment:
      <<: *environment-defaults

volumes:
  static_volume: