# Generated by Django 5.1.1 on 2024-10-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_userresetpasswordtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userresetpasswordtoken",
            name="token",
            field=models.CharField(max_length=6),
        ),
    ]
