# Generated by Django 5.1.2 on 2024-11-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_userresetpasswordtoken_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("subscriber", "Подписчик"), ("author", "Автор")],
                default="subscriber",
                max_length=15,
            ),
        ),
    ]
