# Generated by Django 5.1.2 on 2024-11-18 05:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userresetpasswordtoken",
            name="token",
            field=models.CharField(
                max_length=6, validators=[django.core.validators.MinValueValidator(6)]
            ),
        ),
    ]
