# Generated by Django 5.1.2 on 2024-11-19 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_userresetpasswordtoken_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="role",
        ),
    ]
