# Generated by Django 5.1.2 on 2024-11-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_remove_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
